# Generated by Django 4.0.6 on 2022-07-24 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='Email address')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('be2d7bd7-c045-47d9-85df-8536134eb889'), verbose_name='UUID')),
                ('geo', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Geo data')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_device.abstractuser', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
                ('uuid', models.UUIDField(default=uuid.UUID('cd26a538-0983-4a63-820c-dfbc06ec496f'), verbose_name='UUID')),
                ('on_or_off', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=100, verbose_name='Device on or off')),
                ('registered_time', models.DateTimeField(auto_now_add=True, verbose_name='Registered time')),
                ('time_first_reading', models.DateTimeField(auto_now_add=True, verbose_name='Time of first readinf')),
                ('beginning_value', models.IntegerField(verbose_name='Beginning value in meter')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit of meter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_device.abstractuser', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('09bd76f4-8343-400b-86a7-443a6dd8d785'), verbose_name='UUID')),
                ('dev_eui', models.CharField(max_length=20, verbose_name="Device's ID")),
                ('last_value', models.DateTimeField(verbose_name='Time of last reading')),
                ('activated_time', models.DateTimeField(auto_now_add=True, verbose_name='Activation time')),
                ('on_or_off', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=100, verbose_name='Device on or off')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('device_type', models.CharField(max_length=100, verbose_name='Device type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_device.abstractuser', verbose_name='Owner')),
            ],
        ),
    ]
