# Generated by Django 4.0.6 on 2022-07-24 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fd12ef1d-dfeb-42a3-8fb2-a27c1c2b4f74'), verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('311aa339-a930-419e-bf55-178ca856548e'), verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7bf2ba4e-fd8a-4b1c-b49d-236ff02ae782'), verbose_name='UUID'),
        ),
    ]
